### ISSUE TITLE
Record and play back not working

### ISSUE THREAD

**Issue by krakesh92** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#101]
**I'm submitting a ...**  

[ ] bug report   

[ ] feature request  

[ ] support request

**Current behavior**

**Expected behavior**

**Reproduction of the problem with instructions**

**Use case for changing the behavior**

**Please tell us about your environment:**

* **OS :** 

* **JAVA :** 

* **Selenium :**

* **Browser | Driver  :**

**Comment by Shantha93** [comment]
Resolution provided on GitHub.
