### ISSUE TITLE
maven-eclipse-plugin is not compatible with m2e

### ISSUE THREAD

**Issue by Priyanka-Mishra6** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#106]
maven-eclipse-plugin is not compatible with m2e

I'm using eclipse neon and getting the error mentioned above.

**Comment by kumarkrish85** [comment]
Hi Priyanka,

Please try to configure source code in Net beans. Issue is not related to CITS tool. 

Thanks,
Krishna
