### ISSUE TITLE
Platform name is not printed right in the report during grid execution.

### ISSUE THREAD

**Issue by Shantha93** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#120]
[ ] Bug report

**Current behavior**
During grid execution, the platform names appearing in the existing HTML reports are not the right names of the platform (OS) of the client nodes.

**Expected behavior**
Grid execution reports should print the actual client node's OS or platform name in the HTML report.

**Comment by kumarkrish85** [comment]
Please refer this below link

https://github.com/SeleniumHQ/selenium/issues/5941
