### ISSUE TITLE
Getting error org.openqa.selenium.InvalidArgumentException: invalid argument: 'firstMatch' must contain at least one entry

### ISSUE THREAD

**Issue by sijianand** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#122]
I am getting org.openqa.selenium.InvalidArgumentException: invalid argument: 'firstMatch' must contain at least one entry error
Chrome version 75
and updated the chromedriver latest for 75

**Comment by Shantha93** [comment]
For chrome 75, please try with Chrome driver 2.46, this is working in our environment.
