### ISSUE TITLE
CITS with Chrome 76.0.3809.100  not working need to know the prerequisites

### ISSUE THREAD

**Issue by sijianand** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#124]
I'm submitting a ...

[x] bug report

Current behavior
CITS 1.2 with chrome 76 which throws an error

Expected behavior
CITS  should start

Reproduction of the problem with instructions
update the chrome version to 76 and add the driver for new version which throws an error.
Running Iteration 1
Launching Chrome
Launching Local DriverStarting ChromeDriver 75.0.3770.140 (2d9f97485c7b07dc18a74666574f19176731995c-refs/branch-heads/3770@{#1155}) on port 12379
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
2019-08-12 13:25:29:08S -0500 [SEVERE] com.cognizant.cognizantits.engine.core.Task onError:invalid argument: 'firstMatch' must contain at least one entry

**Tried updating the selenium to 3.14 still throws error**  Error willl be No such method ..

Please tell us about your environment:
Windows 10

OS :
Windows 10

JAVA :
Java 1.8

Selenium :
Selenium 3.5.3

Browser | Driver :
Chrome

**Comment by Shantha93** [comment]
Please update the CITS Engine Code,
https://github.com/CognizantQAHub/Cognizant-Intelligent-Test-Scripter/blob/master/Engine/src/main/java/com/cognizant/cognizantits/engine/drivers/WebDriverFactory.java#L191
 
driver = new ChromeDriver(withChromeOptions(caps));

Updated Code

driver = new ChromeDriver(/*withChromeOptions(caps)*/);

Run from the engine and then export the jar for the changes to be reflected. 
This is a temporary fix to execute your test cases in local environment. We will be releasing a patch, which will be available to all users.
