### ISSUE TITLE
Chrome 76 

### ISSUE THREAD

**Issue by sijianand** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#125]
I'm submitting a ...

[x] bug report

Current behavior
1.CITS 1.2 with chrome 76 which is not getting maximized 
2.Also whether the chrome 76 changes works with all other versions example chrome 75??

Expected behavior
CITS should get maximized

Reproduction of the problem with instructions
When I run the test chrome 76 which is not getting maximized when I change the maximize variable in webdriverfactory true its works is that the solution ??  

Please tell us about your environment:
Windows 10

OS :
Windows 7

JAVA :
Java 1.8

Selenium :
Selenium 3.5.3

Browser | Driver :
Chrome

**Comment by Shantha93** [comment]
Chrome 76 has known issues with Selenium 3.5.3. This is a duplicate query, refer here,
https://github.com/CognizantQAHub/Cognizant-Intelligent-Test-Scripter/issues/124
