### ISSUE TITLE
Run.command execute problem

### ISSUE THREAD

**Issue by unlimitedcode** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#126]
**I'm submitting a ...**  

[ ] bug report   

[ ] feature request  

[ ✔️] support request

**Current behavior**

**Expected behavior**

/Users/mtdp/IdeaProjects/Cognizant-Intelligent-Test-Scripter/Resources/Run.command: line 5: cognizant-intelligent-test-scripter-ide-${project.version}.jar:$APP_CLASSPATH: bad substitution
**Reproduction of the problem with instructions**

**Use case for changing the behavior**

**Please tell us about your environment:**

* **OS :** 

Mac OS
* **JAVA :** 

1.8
* **Selenium :**

* **Browser | Driver  :** 

chrome 70

**Comment by Shantha93** [comment]
Please give permission to access all files in this directory, using "chmod" command. Follow instructions here,
https://github.com/CognizantQAHub/Cognizant-Intelligent-Test-Scripter/blob/master/Resources/Installation.md#launching-ui
