### ISSUE TITLE
Unable to launch the CITS tool

### ISSUE THREAD

**Issue by jayampl** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#128]
**I'm submitting a ...**  

[ ] bug report   
Unable launch CITS tool

**Current behavior**
While clicking on run.bat file,just black screen popping and nothing happens

**Expected behavior**

**Reproduction of the problem with instructions**
 
Step : 1  Downloaded the master from github and extracted the Zip contents
Step : 2  Installed CITS chrome extension 
Step : 3 Imported and installed certificates
Step  4 Launching the CITS app by clicking on run.bat file

**Please tell us about your environment:**
Windows 10 64 bit

* **OS :** 
Windows 10

* **JAVA :** 
Java 1.8

* **Selenium :**

* **Browser | Driver  :** 
Chrome

**Comment by Shantha93** [comment]
This is not an issue.
Please download the CITS release from here,
https://github.com/CognizantQAHub/Cognizant-Intelligent-Test-Scripter/releases
If you are downloading the source code, you need to build the tool using Maven.
