### ISSUE TITLE
Unable to load CITS

### ISSUE THREAD

**Issue by Gnrs25** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#129]
**I'm submitting a ...**  

[ x] bug report   

[ ] feature request  

[ ] support request

**Current behavior**

I am unable to launch CITS app in my desktop. App is not loading. Please check the error log file attached and let me know if this issue is caused by java version? Thanks.
**Expected behavior**

CITS app should be launched successfully on clicking "Run"
**Reproduction of the problem with instructions**

Error log file attached for investigation.

**Use case for changing the behavior**

NA
**Please tell us about your environment:**

* **OS :** 

Windows10
* **JAVA :** 

11.0.3
* **Selenium :**

NA
* **Browser | Driver  :** 

Chrome Version 75.0.3770.90
[log.txt](https://github.com/CognizantQAHub/Cognizant-Intelligent-Test-Scripter/files/3646239/log.txt)

**Comment by kumarkrish85** [comment]
@Gnrs25 This is not an issue, please use Java 8 to launch the IDE. Going forward please raise an issue in google groups. https://groups.google.com/forum/#!forum/cognizant-intelligent-test-scripter

**Comment by Gnrs25** [comment]
Thanks Krishna for the update.
