### ISSUE TITLE
how to create task in CITS for batch run?

### ISSUE THREAD

**Issue by RamaMettukuru** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#135]
**I'm submitting a ...**  

[ ] bug report   

[ ] feature request  

[ ] support request

**Current behavior**

**Expected behavior**

**Reproduction of the problem with instructions**

**Use case for changing the behavior**

**Please tell us about your environment:**

* **OS :** 

* **JAVA :** 

* **Selenium :**

* **Browser | Driver  :**

**Comment by kumarkrish85** [comment]
Schedule or create task in CITS, use Configuration --> Scheduler.  

![schedule](https://user-images.githubusercontent.com/27405093/66894672-a6ca6080-f00e-11e9-96b0-8c9393783035.png)

**Comment by RamaMettukuru** [comment]
I tried..I am getting can not create a task when i am doing the task creation.Please help.Thank you for the response.

**Comment by kumarkrish85** [comment]
Hi @RamaMettukuru ,

I guess the tool folder path length is very big so it fails to create the task. Can you please rename the folder with minimal length? If you still stuck with an issue, share us the logs for analysis

**Comment by RamaMettukuru** [comment]
Thanks Krishan..I tried where i have tool with short path.Able to create.

Can you please help me if i do not want to run,how should i cancel that task.

**Comment by kumarkrish85** [comment]
@RamaMettukuru ,

we have no handle from CITS to cancel the task , please delete it from windows task scheduler

**Comment by RamaMettukuru** [comment]
Thanks a lot..

Can you help if there is any way to reuse test set which has already created one release to another release.

**Comment by kumarkrish85** [comment]
No, we can't reuse. If any clarification please raise a query in  our open forum
[https://groups.google.com/forum/#!forum/cognizant-intelligent-test-scripter](url)
