### ISSUE TITLE
Angular Controls

### ISSUE THREAD

**Issue by sijianand** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#138]
**I'm submitting a ...**  

[ ] bug report   

[ ] feature request  How Can we add angular support to existing CITS? We do have lots of dynamic controls and CITS could nt Identify.

[ ] support request

**Current behavior**

**Expected behavior**

**Reproduction of the problem with instructions**

**Use case for changing the behavior**

**Please tell us about your environment:**

* **OS :** 

* **JAVA :** 

* **Selenium :**

* **Browser | Driver  :**

**Comment by sara-suku** [comment]
Hi,

CITS supports angular automation leveraging ngwebdriver. 

You can find the list of attributes by which you can find angular elements
https://github.com/CognizantQAHub/Cognizant-Intelligent-Test-Scripter/blob/master/Engine/src/main/java/com/cognizant/cognizantits/engine/drivers/findObjectBy/AngularFindBy.java 

You can also refer the DemoProject - AngularJS_Support Testcase.

For any CITS queries, please contact us 
https://github.com/CognizantQAHub/Cognizant-Intelligent-Test-Scripter#contact 

Thanks
CITS Team.
