### ISSUE TITLE
Unable to configure "Appium desktop", directly from the tool IDE, in Windows.

### ISSUE THREAD

**Issue by Shantha93** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#46]
[x] bug report

Environment Details:

Appium version - 1.6.5v (Appium desktop)
Windows system

Bug Details:

When Appium desktop installation location is given under "Configuration>Start server", "Node binary not found" error is thrown in the tool UI.

![appiumdesktopbug](https://user-images.githubusercontent.com/29483663/28064147-277e9722-6651-11e7-9a0c-35e672827f07.png)

**Comment by x0156** [comment]
appium-desktop is a GUI only app. there is no cli / node binary at the moment , you can start the server and follow the same process though. to quote the appium project lead,
`"...appium desktop was designed specifically to not be run programmatically..."` 
see issue appium/appium-desktop/issues/181

**Comment by Shantha93** [comment]
As explained in the above link and in other sources, this is a limitation or constraint from Appium (Desktop version) itself.
Nevertheless, the UI to start  Appium directly from Cognizant Intelligent Test Scripter is not redundant, since it can still be used for Appium CLI versions on Windows.
So closing the issue!
