### ISSUE TITLE
In Exploratory testing , JIRA Configure fields the newly created field cannot be removed. 

### ISSUE THREAD

**Issue by Kitcha85** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#47]
[x ] bug report 

**Current behavior**
The Deleted JIRA field shows up in the relaunch

**Expected behavior**
The field should be deleted in the fields table and removed in Report Bug dialog as well

**Reproduction of the problem with instructions**
1) Click on Tools --> Exploratory testing
2) Click on Settings 
3) Click on "Configure JIRA Fields"
4) Create the new field called "test" and enter the required details. Verify the new field in Report Bug Dialog as well 
5) Perform step 2 and 3
6) Delete the newly created field "test" and save 
7) Close and reopen the dialog the deleted field is still present

**Use case for changing the behavior**
Checking creation JIRA fields

**Please tell us about your environment:**

OS Name         : Windows 7
OS Version      : 6.1
OS Architecture : x86

* **OS :** 

* **JAVA :** 
Java 1.8

**Comment by Shantha93** [comment]
The issue is recurring, the deleted fields ares still visible even after saving them.

**Comment by Shantha93** [comment]
The issue is recurring, the deleted fields ares still visible even after saving them.
