### ISSUE TITLE
Add UI Validation for Condition Field in TestDesign Panel

### ISSUE THREAD

**Issue by Kitcha85** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#48]
[x] bug report 

**Current behavior**
assertElementNear action is not showing mandatory notification in Test Design table. It fails in the run by saying "Required secondary object name"

**Expected behavior**
It needs to enforce the second object name

**Reproduction of the problem with instructions**
1) Create a Test case 
2) Add a step with an action "assertElementNear" , it enforces only the primary object name.

**Use case for changing the behavior**
1) In Action documentation it mentioned about second object name

* **OS :** 

OS Name         : Windows 7
OS Version      : 6.1
OS Architecture : x86

* **JAVA :** 
 Java 1.8

**Comment by phystem** [comment]
@Kitcha85 *It needs to enforce the second object name*. What does enforce means?  What is the *it* mentioned here?  Can you explain the issue more?  If possible attach screenshots. 
Is this happening with *assertElementNear* or other actions well?

**Comment by Kitcha85** [comment]
@phystem Cognizant Intelligent Test Scripter UI needs to enforce the user to add second object. It's happening to almost all the actions in Layout. Please refer the attached Screen shot

![layout](https://user-images.githubusercontent.com/29482975/28166539-eb241242-67f5-11e7-98b0-80d055048bc2.png)
