### ISSUE TITLE
Page Could not be renamed to expected name

### ISSUE THREAD

**Issue by phystem** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#53]
[x] bug report 

Everything mentioned below is with respect to WebObject Repository. Haven't tried with Image/Mobile.

When I try to rename a Page with a name for ex: Test. The Tools shows a popup saying the Page is already Present.

Then I remembered, I previously had a Page with that Name and deleted it down the line.

It only happens when a Page is renamed with a previously deleted Page.

On further investigation, I found that, for each Page that is created, an respective Folder is created inside a folder named `ObjectRepository`. However on deleting the same is not deleting the folders which were created earlier. Coz of that when I try to rename a Page, for which the folder is already present in `ObjectRepository` Folder. It is not allowing me to do so

**Current behavior**
 - When Page is deleted, respective folder is not deleted from the backend.
 - Says Page with Name already Present on renaming

**Expected behavior**
 - Should delete the respective folder  from the backend.
 - Should rename the Page to the expected Page Name.

**Reproduction of the problem with instructions**

![issue](https://user-images.githubusercontent.com/11405204/28216052-c4680aa4-68cd-11e7-9845-c5603b83135a.gif)

**Use case for changing the behavior**
Could not create a Page with a name I want.

**Environment:**
Windows 10
Java 1.8.131 - 64bit
**Build Version:** 1.0 
**Build Date:** 2017-06-20 14:35 UTC 
**Java:** C:\Program Files\Java\jre1.8.0_131

**Comment by x0156** [comment]
@phystem  did `save` project solves the issue?

**Comment by phystem** [comment]
@x0156  Nope. Not working
