### ISSUE TITLE
When I run the DEMO scripts in FireFox, it got crashed.

### ISSUE THREAD

**Issue by flyingsg** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#54]
**I'm submitting a ...**  
```
- [X] bug report 
```

**Current behavior**

When I run the DEMO scripts in FireFox, it got crashed.

**Expected behavior**

**Reproduction of the problem with instructions**

**Use case for changing the behavior**

**Please tell us about your environment:**

* **OS :** 

* **JAVA :** 

* **Selenium :**

* **Driver :** 

* **FireFox :** 
Version: 54.0.1 32 bit

**Comment by phystem** [comment]
Can you update other environment details as well?
Also provide the log generated during execution? You can see the log during execution by clicking the  ![Console](https://raw.githubusercontent.com/CognizantQAHub/Cognizant-Intelligent-Test-Scripter/master/IDE/src/main/resources/ui/resources/toolbar/console.png) icon
Which DemoTestCase you've executed [ScenarioName & TestCaseName]?
Is it working with other browsers?

**Comment by flyingsg** [comment]
@phystem  I only tried Firefox.
the log is listed as following:
Run Information
========================
cognizant.intelligent.test.scripter.engine : 1.0
java.runtime.name    : Java(TM) SE Runtime Environment
java.version         : 1.8.0_131
java.home            : C:\Program Files\Java\jre1.8.0_131
os.name              : Windows 7
os.arch              : amd64
os.version           : 6.1
file.encoding        : UTF-8
========================
Run Started on Wed Jul 19 15:03:51 CST 2017
Loading Browser Profile
Loading RunManager
[Scenario:AccessibilityTesting] [TestCase: AccessibilityActions] [Description: Test Run] [Browser: Firefox] [BrowserVersion: default] [Platform: ANY][ExistingBrowser: false]
Initializing Report
ApiLink not available!!
Shutting Down Thread as there is no need for SelectiveThreading
Running Iteration 1
Launching Firefox
Launching Local Driver
1500447834703	geckodriver	INFO	Listening on 127.0.0.1:42807
1500447835767	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1500447839037	addons.manager	DEBUG	Application has been upgraded
1500447839778	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1500447839785	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1500447839797	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1500447839803	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1500447839806	addons.manager	DEBUG	Starting provider: XPIProvider
1500447839809	addons.xpi	DEBUG	startup
1500447839811	addons.xpi	INFO	Removing all system add-on upgrades.
1500447839811	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1500447839828	addons.xpi	INFO	Mapping aushelper@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1500447839829	addons.xpi	INFO	Mapping e10srollout@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1500447839829	addons.xpi	INFO	Mapping firefox@getpocket.com to C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1500447839829	addons.xpi	INFO	Mapping screenshots@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\screenshots@mozilla.org.xpi
1500447839830	addons.xpi	INFO	Mapping webcompat@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1500447839847	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1500447839848	addons.xpi	DEBUG	checkForChanges
1500447839848	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1500447839848	addons.xpi	DEBUG	Loaded add-on state from prefs: {}
1500447839849	addons.xpi	DEBUG	New add-on aushelper@mozilla.org in app-system-defaults
1500447839850	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1500447839850	addons.xpi	DEBUG	New add-on e10srollout@mozilla.org in app-system-defaults
1500447839851	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1500447839851	addons.xpi	DEBUG	New add-on firefox@getpocket.com in app-system-defaults
1500447839852	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1500447839852	addons.xpi	DEBUG	New add-on screenshots@mozilla.org in app-system-defaults
1500447839853	addons.xpi	DEBUG	getModTime: Recursive scan of screenshots@mozilla.org
1500447839853	addons.xpi	DEBUG	New add-on webcompat@mozilla.org in app-system-defaults
1500447839853	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1500447839854	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1500447839854	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1500447839855	addons.xpi	DEBUG	getInstallState changed: true, state: {"app-system-defaults":{"aushelper@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\aushelper@mozilla.org.xpi","st":1499322317647},"e10srollout@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\e10srollout@mozilla.org.xpi","st":1499322317474},"firefox@getpocket.com":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\firefox@getpocket.com.xpi","st":1499322317315},"screenshots@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\screenshots@mozilla.org.xpi","st":1498612865293},"webcompat@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\webcompat@mozilla.org.xpi","st":1499322316040}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","st":1499322318339}}}
1500447839886	addons.xpi-utils	DEBUG	Opening XPI database C:\Users\C5023796\AppData\Local\Temp\rust_mozprofile.1K06cRnA4lLC\extensions.json
1500447839889	addons.xpi-utils	DEBUG	New add-on aushelper@mozilla.org installed in app-system-defaults
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1500447839920	DeferredSave.extensions.json	DEBUG	Save changes
1500447839922	addons.xpi-utils	DEBUG	New add-on e10srollout@mozilla.org installed in app-system-defaults
1500447839941	DeferredSave.extensions.json	DEBUG	Starting timer
1500447839942	DeferredSave.extensions.json	DEBUG	Save changes
1500447839943	addons.xpi-utils	DEBUG	New add-on firefox@getpocket.com installed in app-system-defaults
1500447839977	DeferredSave.extensions.json	DEBUG	Save changes
1500447839977	addons.xpi-utils	DEBUG	New add-on screenshots@mozilla.org installed in app-system-defaults
1500447839997	DeferredSave.extensions.json	DEBUG	Save changes
1500447839999	addons.xpi-utils	DEBUG	New add-on webcompat@mozilla.org installed in app-system-defaults
1500447840024	DeferredSave.extensions.json	DEBUG	Save changes
1500447840024	addons.xpi-utils	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1500447840036	DeferredSave.extensions.json	DEBUG	Save changes
1500447840038	addons.manager	DEBUG	Registering startup change 'installed' for aushelper@mozilla.org
1500447840047	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1500447840053	addons.xpi	DEBUG	Calling bootstrap method install on aushelper@mozilla.org version 2.0
1500447840053	addons.xpi-utils	DEBUG	Make addon app-system-defaults:aushelper@mozilla.org visible
1500447840054	DeferredSave.extensions.json	DEBUG	Save changes
1500447840055	addons.manager	DEBUG	Registering startup change 'installed' for e10srollout@mozilla.org
1500447840055	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1500447840058	addons.xpi	DEBUG	Calling bootstrap method install on e10srollout@mozilla.org version 1.50
1500447840059	addons.xpi-utils	DEBUG	Make addon app-system-defaults:e10srollout@mozilla.org visible
1500447840060	DeferredSave.extensions.json	DEBUG	Save changes
1500447840061	addons.manager	DEBUG	Registering startup change 'installed' for firefox@getpocket.com
1500447840061	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1500447840068	addons.xpi	DEBUG	Calling bootstrap method install on firefox@getpocket.com version 1.0.5
1500447840068	addons.xpi-utils	DEBUG	Make addon app-system-defaults:firefox@getpocket.com visible
1500447840069	DeferredSave.extensions.json	DEBUG	Save changes
1500447840069	addons.manager	DEBUG	Registering startup change 'installed' for screenshots@mozilla.org
1500447840069	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\screenshots@mozilla.org.xpi
1500447840072	addons.xpi	DEBUG	Calling bootstrap method install on screenshots@mozilla.org version 6.6.0
1500447840073	addons.xpi-utils	DEBUG	Make addon app-system-defaults:screenshots@mozilla.org visible
1500447840073	DeferredSave.extensions.json	DEBUG	Save changes
1500447840073	addons.manager	DEBUG	Registering startup change 'installed' for webcompat@mozilla.org
1500447840074	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1500447840077	addons.xpi	DEBUG	Calling bootstrap method install on webcompat@mozilla.org version 1.1
1500447840077	addons.xpi-utils	DEBUG	Make addon app-system-defaults:webcompat@mozilla.org visible
1500447840078	DeferredSave.extensions.json	DEBUG	Save changes
1500447840078	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1500447840079	DeferredSave.extensions.json	DEBUG	Save changes
1500447840079	addons.xpi	DEBUG	Updating XPIState for {"id":"aushelper@mozilla.org","syncGUID":"{deb0c0b8-8927-4584-a4bc-611dd30391a2}","location":"app-system-defaults","version":"2.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Application Update Service Helper","description":"Sets value(s) in the update url based on custom checks.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\aushelper@mozilla.org.xpi","installDate":1499322317647,"updateDate":1499322317647,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":8488,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0.1","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1500447840079	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1500447840080	addons.xpi	DEBUG	Updating XPIState for {"id":"e10srollout@mozilla.org","syncGUID":"{41b4ec8e-c551-4fee-a689-036dbf0429f4}","location":"app-system-defaults","version":"1.50","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Multi-process staged rollout","description":"Staged rollout of Firefox multi-process feature.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\e10srollout@mozilla.org.xpi","installDate":1499322317474,"updateDate":1499322317474,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":12519,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0.1","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1500447840080	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1500447840080	addons.xpi	DEBUG	Updating XPIState for {"id":"firefox@getpocket.com","syncGUID":"{7c943874-6893-42f8-bd00-0f8401462866}","location":"app-system-defaults","version":"1.0.5","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Pocket","description":"When you find something you want to view later, put it in Pocket.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\firefox@getpocket.com.xpi","installDate":1499322317315,"updateDate":1499322317315,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":913952,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0.1","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1500447840093	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1500447840094	addons.xpi	DEBUG	Updating XPIState for {"id":"screenshots@mozilla.org","syncGUID":"{bf34fc84-f4cb-4304-a431-ef586f6ac197}","location":"app-system-defaults","version":"6.6.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox Screenshots","description":null,"creator":null,"homepageURL":"https://pageshot.net/"},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\screenshots@mozilla.org.xpi","installDate":1498612865293,"updateDate":1498612865293,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":716271,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"51.0a1","maxVersion":"*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1500447840094	addons.xpi	DEBUG	getModTime: Recursive scan of screenshots@mozilla.org
1500447840095	addons.xpi	DEBUG	Updating XPIState for {"id":"webcompat@mozilla.org","syncGUID":"{c2daa990-8dc4-4bc2-841c-8b30551e89a1}","location":"app-system-defaults","version":"1.1","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Web Compat","description":"Urgent post-release fixes for web compatibility.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\webcompat@mozilla.org.xpi","installDate":1499322316040,"updateDate":1499322316040,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":9006,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0.1","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1500447840095	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1500447840097	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"{b60a4f80-c75f-4b83-9945-19055b52f53d}","location":"app-global","version":"54.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":"chrome://browser/content/default-theme-icon.svg","icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1499322318339,"updateDate":1499322318339,"applyBackgroundUpdates":1,"skinnable":true,"size":8207,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0.1","maxVersion":"54.0.1"}],"targetPlatforms":[],"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"userPermissions":null}
1500447840097	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1500447840098	DeferredSave.extensions.json	DEBUG	Save changes
1500447840098	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1500447840111	addons.xpi-utils	DEBUG	Updating add-on states
1500447840132	addons.xpi-utils	DEBUG	Writing add-ons list
1500447840140	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1500447840140	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 2.0
1500447840142	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1500447840143	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.50
1500447840144	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1500447840145	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1500447840146	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\screenshots@mozilla.org.xpi
1500447840147	addons.xpi	DEBUG	Calling bootstrap method startup on screenshots@mozilla.org version 6.6.0
1500447840147	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1500447840148	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.1
1500447840251	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1500447840253	addons.manager	DEBUG	Provider finished startup: XPIProvider
1500447840254	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1500447840254	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1500447840255	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1500447840256	addons.manager	DEBUG	Starting provider: GMPProvider
1500447840269	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1500447840270	addons.manager	DEBUG	Provider finished startup: GMPProvider
1500447840270	addons.manager	DEBUG	Starting provider: PluginProvider
1500447840270	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1500447840271	addons.manager	DEBUG	Provider finished startup: PluginProvider
1500447840271	addons.manager	DEBUG	Completed startup sequence
1500447843447	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1500447843447	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1500447843447	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1500447844431	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1500447844431	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1500447844431	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1500447844435	DeferredSave.extensions.json	DEBUG	Starting write
1500447844977	DeferredSave.extensions.json	DEBUG	Write succeeded
1500447844978	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
1500447860973	Marionette	INFO	Listening on port 53867
1500447861187	Marionette	WARN	TLS certificate errors will be ignored for this session
1500447861377	Marionette	DEBUG	loaded listener.js
2017-07-19 15:04:22:07S +0800 [INFO] org.openqa.selenium.remote.ProtocolHandshake createSession:Detected dialect: W3C

Firefox Launched
Step:1   | Object: Browser | Action: Open | Input: @https://www.bing.com | Conditon:  | @19-Jul-2017 15:04:22.0221500447862863	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1500447863589	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1500447863589	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1500447864358	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.bing.com/"
1500447864407	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.bing.com/"

[DONE]   | Opened Url: https://www.bing.com

===================================================================================================

Step:2   | Object: Browser | Action: testAccessibility | Input: @Bing All | Conditon:  | @19-Jul-2017 15:04:24.024
[WARNING]   | Bing All - Failed 4 violations found 

===================================================================================================

Step:3   | Object: Browser | Action: testAccessibility | Input: @Bing Include @include span,a | Conditon:  | @19-Jul-2017 15:04:25.025
[WARNING]   | Bing Include - Failed 4 violations found 

===================================================================================================

Step:4   | Object: Browser | Action: testAccessibility | Input: @Bing Exclude @exclude a | Conditon:  | @19-Jul-2017 15:04:27.027
[WARNING]   | Bing Exclude - Failed 5 violations found 

===================================================================================================

Step:5   | Object: Browser | Action: testAccessibility | Input: @Bing InExclude @include span, a @exclude p | Conditon:  | @19-Jul-2017 15:04:28.028
[WARNING]   | Bing InExclude - Failed 4 violations found 

===================================================================================================

Step:6   | Object: Browser | Action: testAccessibility | Input: @BingOptions @options {runOnly:{type: "tag", values:["wcag2a"]}} | Conditon:  | @19-Jul-2017 15:04:28.028
[WARNING]   | BingOptions - Failed 5 violations found 

===================================================================================================

Step:7   | Object: BingMenu | Action: testAccessibilityElement | Input:  | Conditon:  | @19-Jul-2017 15:04:29.029
Using @id [sc_hdu], Object 'BingMenu' Found in 12 ms
[WARNING]   | BingMenu - Failed 1 violations found 

===================================================================================================

Step:8   | Object: Sign in | Action: testAccessibilityElement | Input: @CustomName | Conditon:  | @19-Jul-2017 15:04:29.029
Using @id [id_l], Object 'Sign in' Found in 5 ms
[DONE]   | CustomName - Passed all the recommendations by aXe

===================================================================================================

Step:9   | Object: BindDisplay | Action: testAccessibilityElement | Input:  | Conditon:  | @19-Jul-2017 15:04:29.029
Using @type [div], Object 'BindDisplay' Found in 46 ms
[DONE]   | BindDisplay - Passed all the recommendations by aXe

===================================================================================================
1500447870114	Marionette	INFO	New connections will no longer be accepted
1500447870143	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.1
1500447870144	addons.xpi	DEBUG	Calling bootstrap method shutdown on screenshots@mozilla.org version 6.6.0
1500447870145	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.5
1500447870147	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.50
1500447870149	addons.xpi	DEBUG	Calling bootstrap method shutdown on aushelper@mozilla.org version 2.0
2017-07-19 15:04:34:07S +0800 [SEVERE] org.openqa.selenium.os.UnixProcess destroy:Unable to kill process with PID 11932


---------------------------------------------------
Testcase Name        : AccessibilityTesting:AccessibilityActions
Executed Steps       : 9
Passed Steps         : 3
Failed Steps         : 6
Time Taken           : 00:00:42
-----------------------------------------------------

Run Finished on Wed Jul 19 15:04:34 CST 2017
Performance log not found. Make sure "capturePageTimings" action is included in testcase. 
-----------------------------------------------------
ExecutionDate        : 19-Jul-2017 15-03-51
Executed TestCases   : 1
Passed TestCases     : 0
Failed TestCases     : 1
Time Taken           : 00:00:43
ReportPath           : file:///D:\temp\cognizant-intelligent-test-scripter-1.0-setup\cognizant-intelligent-test-scripter-1.0\Projects\DemoProject\Results\TestDesign\AccessibilityTesting\AccessibilityActions\19-Jul-2017 15-03-51\summary.html
-----------------------------------------------------

**Comment by phystem** [comment]
@flyingsg  This seems to be an issue with GeckoDriver. Can you post any screenshot of firefox crashing?
Also can you check and confirm if this is related to https://github.com/mozilla/geckodriver/issues/387 and https://github.com/seleniumhq/selenium/issues/2701.

P.S : From the Console it seems you are using 64 bit Os `os.arch              : amd64` . And you have mentiond you are using Firefox 32 bit version [`54.0.1 32 bit`] . Can you upgrade to Firefox 64 bit and confirm the same is happening.

**Comment by flyingsg** [comment]
![crash](https://user-images.githubusercontent.com/2092956/28357180-2821771a-6c9d-11e7-9d29-7608f9cee0f9.png)

**Comment by phystem** [comment]
@flyingsg This seems to be an open issue with GeckoDriver https://github.com/mozilla/geckodriver/issues/285 .  So we can't do much from our end.
As requested upgrade your firefox and confirm if the same is happening.
Have you tried running other testcases and the result is same on that as well?

**Comment by phystem** [comment]
Closing due to less information

**Comment by phystem** [comment]
Closing due to less information
