### ISSUE TITLE
failed step in `reusable` doesn't break `testcase` execution 

### ISSUE THREAD

**Issue by x0156** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#59]
**I'm submitting a ...**  
```
[x] bug report   
```
**Current behavior**
failed step in `reusable` does't break `testcase` execution when `BreakOnError` Enabled

**Expected behavior**
 `testcase` execution should stop on step fail when `BreakOnError` Enabled

**Reproduction of the problem with instructions**

1.  Create a `testcase` with `reusable`
2.  Make sure a step inside the `reusable`  fails
3.  Enable `BreakOnError` and Start Execution
4. You will find execution stops at `reusable` step but continues to rest of the `testcase`

**Use case for changing the behavior**

`BreakOnError` should stop the execution of the `testcase`

**Comment by Shantha93** [comment]
Working as expected now.

**Comment by Shantha93** [comment]
If the step inside reusable component, fails due to an "element identification" issue or error, the expected behavior is not achieved, that is the execution of the steps outside the reusable component still continues.

**Comment by x0156** [comment]
execution breaks as expected, looks like some actions `select` actions in particular doesn't behave as expected (it doesn't throw the `ElementException` hence act as optional step like `selectIfExist`) , so it doesn't break the execution.

**Comment by Shantha93** [comment]
Raising it as  a new issue. Refer issue  #87
