### ISSUE TITLE
Wrong status displayed for failed `Reusable`

### ISSUE THREAD

**Issue by NanawareAmol** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#62]
**I'm submitting a ...** 

[x] bug report

**Current behavior**
   Failed step of `reusable` in reports getting displayed outside the reusable steps which is making failed 
   reusable status as `pass`

**Expected behavior**
   Failed step of `reusable` in reports should be displayed under the reusable section and the 
   status should be displayed as `fail`.

**Reproduction of the problem with instructions**
   1.    Create a `testcase` with reusable
   2.    Make sure a step inside the `reusable` fails
   3.    Start Execution
   4.    You will find that the `reusable` status as `pass` instead of failed and the failed step is 
          displayed outside of that `reusable` section

**Use case for changing the behavior**
   Failed `reusable` step should be displayed under `reusable` section and the status should be updated 
   correctly.

**Comment by x0156** [comment]
when `reusable` step fails while on `BreakOnError` the execution of further steps including `reusable` breaks before updating the status of the step in `report` and it is updated as in the root `testcase` thus the reusable   status is the refreshed.
