### ISSUE TITLE
Error in running the CITS Task from Task Scheduler

### ISSUE THREAD

**Issue by Kitcha85** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#83]
[X] bug report   

Scheduler configured through CITS in windows 10 is not running. But when trying to execute the script in command line works fine.

**Current behavior**
The Run operation in the task is not working as expected

**Expected behavior**
CITS Task scheduled in the windows 10 should run. 

**Reproduction of the problem with instructions**
1. Launch CITS
2. Have release, testset(s) in your project
3. Configure scheduler from CITS
4. Verify the task is listed in Task scheduler
5. Run the task configured through CITS

* **OS :** 
Windows 10

* **JAVA :** 
JDK 1.8

**Comment by phystem** [comment]
If there is any **space in filepath** where CITS is installed, it has to be escaped with double quotes. Also the arguments has to be escaped incase of spaces. 
But in **Windows 10** it is **not accepting quotes** in both Program Name(Run.bat location) and arguments. So quotes has to be removed from one of them.

As a workaround put the CITS in a filepath without spaces and **remove quotes** by editing the task manually.

![fff](https://user-images.githubusercontent.com/11405204/29168563-058d41be-7ded-11e7-8956-3a64454f9dbd.gif)

**Comment by phystem** [comment]
Asked a query in SO https://stackoverflow.com/questions/45612215/task-scheduler-arguments-with-quotes-not-working

As mentioned going to change the arguments and syntax.

**Comment by Shantha93** [comment]
No code change is done since the above issue is specific to the environment. However the above workaround works as expected and can be followed for above environment.
