### ISSUE TITLE
clicking the extension in chrome throws error 

### ISSUE THREAD

**Issue by franxav123** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#84]
**I'm submitting a ...**  

[ ] bug report   

[ ] feature request  

[Yes ] support request

**Current behavior**
Not opening browser to perform actions

**Expected behavior**
 To open the browser successfully

**Reproduction of the problem with instructions**

**Use case for changing the behavior**

**Please tell us about your environment:**

* **OS :** 

* **JAVA :** 

* **Selenium :**

* **Browser | Driver  :** 
Chrome

**Comment by phystem** [comment]
For support related questions raise it in [Google Groups](https://groups.google.com/forum/#!forum/cognizant-intelligent-test-scripter) or [Gitter](https://gitter.im/Cognizant-Intelligent-Test-Scripter/lobby)

You can follow the [Help Doc](https://cognizantqahub.github.io/Cognizant-Intelligent-Test-Scripter-Helpdoc/faq/addon/index.html)

We Can't make anything out, from the current details you've provided.  Provide more info. Refer [CONTRIBUTING](https://github.com/CognizantQAHub/Cognizant-Intelligent-Test-Scripter/blob/master/CONTRIBUTING.md#reporting-bugs)

We are closing this for the moment. Update your question with more info and reopen if you want.
