### ISSUE TITLE
Abnormal behavior while iterating the test steps

### ISSUE THREAD

**Issue by Shantha93** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#85]
[ yes ] bug report   

**Current behavior**
When the iteration count condition  is complete,  the execution does not stop immediately but stops only when a step taking data from data sheet is encountered.

**Expected behavior**
Iteration (looping or parameterization) should execute the steps for a fixed (or given) number of times only and should not execute any additional steps

Attaching the console log for a scenario in which only the first 4 steps were executed for 2 sets of data from the data sheet but the execution breaks only when the step with test data (from the data sheet) is executed.
[console.txt](https://github.com/CognizantQAHub/Cognizant-Intelligent-Test-Scripter/files/1259827/console.txt)

**Comment by x0156** [comment]
currently `sub-iteration` without iteration limit (dynamic) will stop only when it encounters `DataNotFoundException`  and its a limitation by design .
