### ISSUE TITLE
Unable to integrate with JIRA latest version (with latest Zephyr and Zapi addon configured) from CITS IDE

### ISSUE THREAD

**Issue by Shantha93** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#86]
[yes ] feature request  

**Current behavior**
The latest version of JIRA has some new parameters that are yet to be handled in the CITS Engine and hence not able to establish the integration with latest JIRA from the existing  CITS engine code

**Expected behavior**
Integration with latest JIRA should be working fine from CITS tool

**Comment by x0156** [comment]
The rest endpoint to update test results in jira-zephyr has been changes from `rest/zapi/latest/execution/{{eid}}/quickExecute` to `rest/zapi/latest/execution/{{eid}}/execute` and the request method changed from `post`  to `put` , this changes need to be updated in `sync` module

**Comment by Shantha93** [comment]
:+1:
