### ISSUE TITLE
Option to do partial image comparison

### ISSUE THREAD

**Issue by Shantha93** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#92]
[ Yes] feature request  

**Current behavior**
The galen action "assertelementimage" currently compares the whole image with no option to restrict specific regions in the image

**Expected behavior**
The action can be extended to compare specific portions of the image instead of the whole image.

**Comment by x0156** [comment]
`exclude-objects` option is added in newer Galen version. will add it to the `assertElementImage` as well.
