### ISSUE TITLE
Cucumber style BDD report working only for one level of reusable component.

### ISSUE THREAD

**Issue by Shantha93** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#95]
[yes ] bug report   

If a BDD test case in CITS contains more on one level of reusable components, the BDD report icon in the CITS HTML report is not opening and throwing exceptions in the console (attached).

[attachments.zip](https://github.com/CognizantQAHub/Cognizant-Intelligent-Test-Scripter/files/1469817/attachments.zip)

**Comment by x0156** [comment]
Current cucumber report (from cits) implementation doesn't support bdd test cases with multi level reusables. Thus leads to the error on report. Need to update the conversion to consider the above case.

**Comment by Shantha93** [comment]
Working 👍
