### ISSUE TITLE
Ignore protected mode setting in IE

### ISSUE THREAD

**Issue by eric-stanley** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#98]
**I'm submitting a...**  

[ x ] bug report   

[ x ] feature request  

[  ] support request

**Current behavior**
 Not able to ignore protected mode settings from IDE (and) no documentation to create a sample testcase from scratch

**Expected behavior**
 User should be able to add browser specific capabilities, as browser capabilities are might differ for enterprises

**Reproduction of the problem with instructions**
 This his does not occur always across browsers. Issue occurs only when user is not able to change protected mode setting in IE and has no option but to override it within the code.

**Use case for changing the behavior**
 User should be provided with option to provide browser specific capabilities in IDE. Also, a video/document on how to write a simple testcase from scratch would be helpful

**Please tell us about your environment:**

* **OS :** 
 Windows 7

* **JAVA :** 
 1.8

* **Selenium :**
 3.5.3

* **Browser | Driver  :** 
 IE 11

**Comment by TN-74** [comment]
Hi @eric-stanley Looks like what you are looking for is here **Configuration -> Browser Configuration -> Capabilities**.
