### ISSUE TITLE
Installation on Mac 

### ISSUE THREAD

**Issue by Tanmoyray** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter#99]
Tanmoys-Mac-mini:Extensions tanmoyray$ xattr -d -r com.apple.quarantine /path/to/cognizant-intelligent-test-scripter
xattr: No such file: /path/to/cognizant-intelligent-test-scripter
Tanmoys-Mac-mini:Extensions tanmoyray$ 

-->

[ ] bug report   
 xattr -d -r com.apple.quarantine /path/to/cognizant-intelligent-test-scripter
xattr: No such file: /path/to/cognizant-intelligent-test-scripter

when i click on Run.command then i received a error: 

Tanmoys-Mac-mini:~ tanmoyray$ /Users/tanmoyray/Documents/Cognizant-Intelligent-Test-Scripter-master/Resources/Run.command ; exit;
/Users/tanmoyray/Documents/Cognizant-Intelligent-Test-Scripter-master/Resources/Run.command: line 5: cognizant-intelligent-test-scripter-ide-${project.version}.jar:$APP_CLASSPATH: bad substitution
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by Shantha93** [comment]
Please follow the installation guide here which covers for Mac environment as well,
https://github.com/CognizantQAHub/Cognizant-Intelligent-Test-Scripter/blob/master/Resources/Installation.md
